In [1]:
import pandas as pd
import numpy as np

In [2]:
text={"text":["people watch Aiyug","Aiyug watch Aiyug","people write comment","Aiyug write comment"],"Output":[1,1,0,0]}

In [3]:
text=pd.DataFrame(text)
text

text  Output
0    people watch Aiyug       1
1     Aiyug watch Aiyug       1
2  people write comment       0
3   Aiyug write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True, stop_words='english', binary=True)
bow=cv.fit_transform(text['text'])
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [5]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [ ]:
cv = CountVectorizer()
cv.fit(["hello my name is aditya", "comment your name", "watch the video"])
vector = cv.transform(["hello comment my name watch is aditya"]).toarray()
print(vector)

[[1 1 1 1 1 1 0 0 1 0]]


In [25]:

from nltk.util import ngrams
from nltk.tokenize import word_tokenize
text = "I love natural language processing "
tokens = word_tokenize(text)
n = 3
bigrams = list(ngrams(tokens, n))
print("bigrams:-", bigrams)


bigrams:- [('I', 'love', 'natural'), ('love', 'natural', 'language'), ('natural', 'language', 'processing')]


In [8]:

from sklearn.feature_extraction.text import TfidfVectorizer
text = ["i love natural language processing", "i love machine learning", "i love deep learning"]
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(text)
# print(tfidf_matrix.toarray())
feature_names = vectorizer.get_feature_names_out()
for doc_index, doc in enumerate(tfidf_matrix.toarray()):
    print("document:-", doc_index + 1)
    for word_index, score in enumerate(doc):
        if score > 0:
            print(f"{feature_names[word_index]}: {score:.4f}")



document:- 1
language: 0.5465
love: 0.3227
natural: 0.5465
processing: 0.5465
document:- 2
learning: 0.5478
love: 0.4254
machine: 0.7203
document:- 3
deep: 0.7203
learning: 0.5478
love: 0.4254


In [ ]:
vectorizer.get_feature_names_out()

array(['deep', 'language', 'learning', 'love', 'machine', 'natural',
       'processing'], dtype=object)

In [ ]:
import spacy

# Load spaCy's small English model
pos = spacy.load('en_core_web_sm')

# Process a sentence
doc = pos("I love natural language processing")


I love natural language processing


In [33]:
doc.text

'I love natural language processing'

In [34]:
doc[3].pos_

'NOUN'

In [35]:
from nltk.stem import PorterStemmer
st=PorterStemmer()
print(st.stem("loving"))

love


In [36]:
print(st.stem("loving"))
st.stem("loving")

love


'love'